CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Denuncias" (
    "Id" text NOT NULL,
    "Creacion" timestamp with time zone NOT NULL,
    "HiloId" text NULL,
    "Motivo" text NULL,
    CONSTRAINT "PK_Denuncias" PRIMARY KEY ("Id")
);

CREATE TABLE "Medias" (
    "Id" text NOT NULL,
    "Creacion" timestamp with time zone NOT NULL,
    "Url" text NULL,
    "VistaPreviaUrl" text NULL,
    "Hash" text NULL,
    "Tipo" integer NOT NULL,
    CONSTRAINT "PK_Medias" PRIMARY KEY ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" text NOT NULL,
    "Creacion" timestamp with time zone NOT NULL,
    "Nick" text NULL,
    "Contraseña" text NULL,
    "Role" integer NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comentarios" (
    "Id" text NOT NULL,
    "Creacion" timestamp with time zone NOT NULL,
    "UsuarioId" text NULL,
    "MediaId" text NULL,
    "Estado" integer NOT NULL,
    "HiloId" text NULL,
    "Contenido" text NULL,
    CONSTRAINT "PK_Comentarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comentarios_Medias_MediaId" FOREIGN KEY ("MediaId") REFERENCES "Medias" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Hilos" (
    "Id" text NOT NULL,
    "Creacion" timestamp with time zone NOT NULL,
    "UsuarioId" text NULL,
    "MediaId" text NULL,
    "Estado" integer NOT NULL,
    "Titulo" text NULL,
    "Contenido" text NULL,
    "CategoriaId" integer NOT NULL,
    "Bump" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Hilos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Hilos_Medias_MediaId" FOREIGN KEY ("MediaId") REFERENCES "Medias" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Comentarios_MediaId" ON "Comentarios" ("MediaId");

CREATE INDEX "IX_Hilos_MediaId" ON "Hilos" ("MediaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20191217022916_primeraMigracion', '3.1.3');

CREATE TABLE "HiloAcciones" (
    "Id" text NOT NULL,
    "Creacion" timestamp with time zone NOT NULL,
    "UsuarioId" text NULL,
    "HiloId" text NULL,
    "Seguido" boolean NOT NULL,
    "Favorito" boolean NOT NULL,
    "Hideado" boolean NOT NULL,
    CONSTRAINT "PK_HiloAcciones" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20191218180909_HiloActions', '3.1.3');

ALTER TABLE "Hilos" ALTER COLUMN "UsuarioId" TYPE text;
ALTER TABLE "Hilos" ALTER COLUMN "UsuarioId" SET NOT NULL;
ALTER TABLE "Hilos" ALTER COLUMN "UsuarioId" DROP DEFAULT;

ALTER TABLE "Hilos" ADD "Ip" inet NULL;

ALTER TABLE "Comentarios" ALTER COLUMN "UsuarioId" TYPE text;
ALTER TABLE "Comentarios" ALTER COLUMN "UsuarioId" SET NOT NULL;
ALTER TABLE "Comentarios" ALTER COLUMN "UsuarioId" DROP DEFAULT;

ALTER TABLE "Comentarios" ALTER COLUMN "HiloId" TYPE text;
ALTER TABLE "Comentarios" ALTER COLUMN "HiloId" SET NOT NULL;
ALTER TABLE "Comentarios" ALTER COLUMN "HiloId" DROP DEFAULT;

ALTER TABLE "Comentarios" ADD "Ip" inet NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20191218201700_ip', '3.1.3');

DROP TABLE "Usuarios";

ALTER TABLE "Medias" DROP COLUMN "VistaPreviaUrl";

ALTER TABLE "AspNetUsers" ADD "Role" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200729073646_Media1', '3.1.3');

ALTER TABLE "AspNetUsers" DROP COLUMN "Role";

CREATE TABLE "Notificaciones" (
    "Id" text NOT NULL,
    "UsuarioId" text NULL,
    "HiloId" text NULL,
    "ComentarioId" text NULL,
    "Tipo" integer NOT NULL,
    "Actualizacion" timestamp with time zone NOT NULL,
    "HiloModelId" text NULL,
    CONSTRAINT "PK_Notificaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notificaciones_Comentarios_ComentarioId" FOREIGN KEY ("ComentarioId") REFERENCES "Comentarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Notificaciones_Hilos_HiloModelId" FOREIGN KEY ("HiloModelId") REFERENCES "Hilos" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Notificaciones_ComentarioId" ON "Notificaciones" ("ComentarioId");

CREATE INDEX "IX_Notificaciones_HiloModelId" ON "Notificaciones" ("HiloModelId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200805002058_notis', '3.1.3');

ALTER TABLE "Notificaciones" ADD "Conteo" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200806011549_conteoNoti', '3.1.3');

CREATE TABLE "Stickies" (
    "HiloId" text NOT NULL,
    "Expiracion" timestamp with time zone NOT NULL,
    "Global" boolean NOT NULL,
    "Importancia" integer NOT NULL,
    CONSTRAINT "PK_Stickies" PRIMARY KEY ("HiloId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201020220034_stickies', '3.1.3');

ALTER TABLE "Comentarios" DROP COLUMN "Estado";

ALTER TABLE "Comentarios" ADD "HiloModelId" text NULL;

CREATE INDEX "IX_Comentarios_HiloModelId" ON "Comentarios" ("HiloModelId");

ALTER TABLE "Comentarios" ADD CONSTRAINT "FK_Comentarios_Hilos_HiloModelId" FOREIGN KEY ("HiloModelId") REFERENCES "Hilos" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201021222554_estado hilo', '3.1.3');

ALTER TABLE "Denuncias" ALTER COLUMN "Motivo" TYPE text;
ALTER TABLE "Denuncias" ALTER COLUMN "Motivo" SET NOT NULL;
ALTER TABLE "Denuncias" ALTER COLUMN "Motivo" DROP DEFAULT;

ALTER TABLE "Denuncias" ALTER COLUMN "HiloId" TYPE text;
ALTER TABLE "Denuncias" ALTER COLUMN "HiloId" SET NOT NULL;
ALTER TABLE "Denuncias" ALTER COLUMN "HiloId" DROP DEFAULT;

ALTER TABLE "Denuncias" ADD "Aclaracion" text NULL;

ALTER TABLE "Denuncias" ADD "ComentarioId" text NULL;

ALTER TABLE "Denuncias" ADD "Estado" integer NOT NULL DEFAULT 0;

ALTER TABLE "Denuncias" ADD "Tipo" integer NOT NULL DEFAULT 0;

ALTER TABLE "Denuncias" ADD "UsuarioId" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201024060547_denuncias', '3.1.3');

